export const aiCareerLabels: Record<string, string> = {
  fullName: 'Họ và tên', email: 'Email', phone: 'Số điện thoại', location: 'Địa điểm',
  linkedIn: 'LinkedIn', portfolio: 'Hồ sơ năng lực', skills: 'Kỹ năng', achievements: 'Thành tựu',
  name: 'Tên', title: 'Tiêu đề', company: 'Công ty', position: 'Vị trí', school: 'Trường học',
  degree: 'Bằng cấp', description: 'Mô tả', duration: 'Thời gian', startDate: 'Bắt đầu', endDate: 'Kết thúc',
  technicalSkills: 'Kỹ năng chuyên môn', experience: 'Kinh nghiệm', education: 'Học vấn',
  projects: 'Dự án', certificates: 'Chứng chỉ', languages: 'Ngoại ngữ', softSkills: 'Kỹ năng mềm',
  keywords: 'Từ khóa', formatting: 'Định dạng CV', keywordRichness: 'Mức độ phong phú từ khóa',
  resumeCompleteness: 'Mức độ hoàn thiện CV', educationQuality: 'Chất lượng học vấn',
  projectRichness: 'Mức độ thể hiện dự án', consistency: 'Tính nhất quán',
  summary: 'Tổng quan', recommendations: 'Đề xuất', risks: 'Điểm cần lưu ý', nextSteps: 'Bước tiếp theo',
  overallEvaluation: 'Đánh giá tổng quan', strengths: 'Điểm mạnh', weaknesses: 'Điểm cần cải thiện',
  highScoreReasons: 'Lý do đạt điểm cao', lowScoreReasons: 'Lý do chưa đạt điểm cao',
  missingTechnologies: 'Công nghệ còn thiếu', careerSuggestions: 'Gợi ý phát triển nghề nghiệp',
  resumeImprovementChecklist: 'Danh sách cải thiện CV', skillRecommendations: 'Gợi ý kỹ năng',
  projectRecommendations: 'Gợi ý dự án', certificationSuggestions: 'Gợi ý chứng chỉ',
  keywordImprovements: 'Cải thiện từ khóa', experienceImprovements: 'Cải thiện kinh nghiệm',
  educationImprovements: 'Cải thiện học vấn', gapExplanations: 'Giải thích khoảng trống',
  learningRoadmap: 'Lộ trình học tập', recommendedTechnologies: 'Công nghệ nên học',
  recommendedCertifications: 'Chứng chỉ nên cân nhắc', portfolioImprovements: 'Cải thiện portfolio',
  recommendationSummary: 'Tóm tắt gợi ý', gapSummary: 'Tóm tắt khoảng trống',
  recommendationReason: 'Lý do gợi ý', interviewRecommendation: 'Gợi ý phỏng vấn',
  technicalQuestions: 'Câu hỏi kỹ thuật', behavioralQuestions: 'Câu hỏi hành vi',
  hrQuestions: 'Câu hỏi nhân sự', projectQuestions: 'Câu hỏi dự án', question: 'Câu hỏi',
  expectedAnswerOutline: 'Dàn ý trả lời', whyInterviewerAsks: 'Mục đích câu hỏi',
  relatedResumeSection: 'Mục CV liên quan', difficulty: 'Độ khó', area: 'Lĩnh vực',
  gap: 'Khoảng trống', explanation: 'Giải thích', priority: 'Mức ưu tiên',
}
