spring:

  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/recruitment_db
    username: recruitment_app
    password: RecruitmentDev_Pg_2026!
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Ho_Chi_Minh

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8081

jwt:
  secret: 4F8A9B72D35E1C847A91F6D28C5B9E73F84A9D21E6C4B7A15D8F2C93E7A4B6F18
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always