spring:

  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]
      - optional:file:../../.env[.properties]

  application:
    name: recruitment-service

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: ${JPA_SHOW_SQL}

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        default_schema: recruitment_service
        format_sql: true
        jdbc:
          time_zone: ${JPA_TIME_ZONE}

  flyway:
    enabled: true
    baseline-on-migrate: true
    create-schemas: true
    schemas: recruitment_service
    default-schema: recruitment_service
    table: recruitment_service_flyway_schema_history
    locations: classpath:db/migration

server:
  port: ${RECRUITMENT_SERVICE_PORT}

services:
  company-service:
    url: ${COMPANY_SERVICE_URL}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

springdoc:

  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

logging:

  level:
    root: INFO
    org.springframework: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

management:

  endpoints:

    web:

      exposure:
        include: health

  endpoint:
    health:
      show-details: never
