spring:

  application:
    name: recruitment-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/recruitment_db}
    username: ${DB_USERNAME:recruitment_app}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        default_schema: recruitment_service
        format_sql: true
        jdbc:
          time_zone: Asia/Ho_Chi_Minh

  flyway:
    enabled: true
    baseline-on-migrate: true
    create-schemas: true
    schemas: recruitment_service
    default-schema: recruitment_service
    table: recruitment_service_flyway_schema_history
    locations: classpath:db/migration

server:
  port: 8084

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000

springdoc:

  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

logging:

  level:
    root: INFO
    org.springframework: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

management:

  endpoints:

    web:

      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always