package com.recruitment.ai.assistant;

public enum RecruiterAssistantTask {
    SUMMARIZE_CANDIDATE,
    SUMMARIZE_JOB,
    EXPLAIN_MATCH_RESULT,
    EXPLAIN_RESUME,
    SUGGEST_INTERVIEW_FOCUS,
    GENERATE_RECRUITER_NOTES,
    GENERATE_HIRING_RECOMMENDATION,
    GENERATE_REJECTION_FEEDBACK,
    GENERATE_IMPROVEMENT_SUGGESTIONS
}
