import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Building2 } from 'lucide-react'
import { useSearchParams } from 'react-router-dom'
import { getErrorMessage } from '../../lib/api/error-adapter'
import { adminCompaniesKey, getAdminCompanies, updateAdminCompanyVerification } from './admin.api'

export function AdminCompaniesPage() {
  const [params, setParams] = useSearchParams(); const page = Math.max(0, Number(params.get('page') || 0)); const keyword = params.get('keyword') || ''; const verificationStatus = params.get('verificationStatus') || ''
  const client = useQueryClient(); const companies = useQuery({ queryKey: [...adminCompaniesKey, page, keyword, verificationStatus], queryFn: () => getAdminCompanies({ page, size: 10, sort: 'createdAt,desc', ...(keyword ? { keyword } : {}), ...(verificationStatus ? { verificationStatus } : {}) }) })
  const verify = useMutation({ mutationFn: ({ id, status }: { id: string; status: string }) => updateAdminCompanyVerification(id, status), onSuccess: () => client.invalidateQueries({ queryKey: adminCompaniesKey }) })
  const update = (next: Record<string, string>) => setParams({ ...(keyword ? { keyword } : {}), ...(verificationStatus ? { verificationStatus } : {}), ...next })
  return <main className="admin-page"><header className="admin-page__hero"><div><span>Business verification</span><h1>Quản lý công ty</h1><p>Kiểm duyệt doanh nghiệp bằng enum PENDING, VERIFIED, REJECTED của Company Service.</p></div><Building2 /></header><section className="admin-toolbar"><label>Tìm kiếm<input value={keyword} onChange={(e) => update({ keyword: e.target.value, page: '0' })} /></label><label>Xác minh<select value={verificationStatus} onChange={(e) => update({ verificationStatus: e.target.value, page: '0' })}><option value="">Tất cả</option><option>PENDING</option><option>VERIFIED</option><option>REJECTED</option></select></label></section>{companies.isError && <p className="admin-feedback admin-feedback--error">{getErrorMessage(companies.error)}</p>}{companies.data && <section className="admin-grid admin-grid--three">{companies.data.content.map((company) => <article className="admin-card" key={company.id}><div className="admin-card__top"><h2>{company.name}</h2><span className={`admin-badge admin-badge--${company.verificationStatus?.toLowerCase()}`}>{company.verificationStatus}</span></div><dl><div><dt>Owner</dt><dd>{company.ownerId}</dd></div><div><dt>Email</dt><dd>{company.email || '—'}</dd></div><div><dt>Status</dt><dd>{company.status}</dd></div></dl><div className="admin-card__actions"><select aria-label={`Xác minh ${company.name}`} value={company.verificationStatus || 'PENDING'} disabled={verify.isPending} onChange={(e) => verify.mutate({ id: company.id, status: e.target.value })}><option>PENDING</option><option>VERIFIED</option><option>REJECTED</option></select></div></article>)}</section>}{companies.data && <nav className="admin-pagination"><button className="admin-button admin-button--secondary" disabled={companies.data.first} onClick={() => update({ page: String(page - 1) })}>Trước</button><span>Trang {companies.data.number + 1}/{Math.max(1, companies.data.totalPages)}</span><button className="admin-button admin-button--secondary" disabled={companies.data.last} onClick={() => update({ page: String(page + 1) })}>Sau</button></nav>}</main>
}
