import { useQuery } from '@tanstack/react-query'
import { AlertCircle, Bot, Cpu, Database, RefreshCw, Server } from 'lucide-react'
import { getErrorMessage } from '../../lib/api/error-adapter'
import { adminProviderKey, getAiProviderInfo } from './admin.api'

export function AdminAiProviderPage() {
  const provider = useQuery({ queryKey: adminProviderKey, queryFn: getAiProviderInfo, retry: false })
  return <main className="admin-page"><header className="admin-page__hero"><div><span>Read-only monitoring</span><h1>AI Provider</h1><p>Thông tin provider, model routing và availability do AI Service công bố. Trang này không thay đổi cấu hình.</p></div><Bot /></header>
    {provider.isPending && <div className="admin-skeleton"><span /><span /></div>}{provider.isError && <section className="admin-state"><AlertCircle /><h2>Không thể đọc trạng thái AI</h2><p>{getErrorMessage(provider.error)}</p><button className="admin-button admin-button--secondary" onClick={() => void provider.refetch()}><RefreshCw />Thử lại</button></section>}
    {provider.data && <><section className="admin-dashboard-grid"><article className="admin-stat"><span><Server /></span><div><small>Provider</small><strong>{provider.data.provider}</strong></div></article><article className="admin-stat"><span><Cpu /></span><div><small>Model</small><strong>{provider.data.model}</strong></div></article><article className="admin-stat"><span><Database /></span><div><small>Deployments</small><strong>{provider.data.enabledModelDeployments}</strong></div></article></section><section className="admin-grid"><article className="admin-card"><div className="admin-card__top"><h2>Runtime</h2><span className={`admin-badge${['ONLINE','CONFIGURED'].includes(provider.data.status) ? '' : ' admin-badge--off'}`}>{provider.data.status}</span></div><dl><div><dt>Phase</dt><dd>{provider.data.phase}</dd></div><div><dt>Endpoint</dt><dd>{provider.data.endpoint}</dd></div><div><dt>Ollama</dt><dd>enabled {String(provider.data.ollamaEnabled)} · configured {String(provider.data.ollamaConfigured)}</dd></div><div><dt>OpenAI</dt><dd>enabled {String(provider.data.openAiEnabled)} · configured {String(provider.data.openAiConfigured)}</dd></div></dl></article><article className="admin-card"><h2>Model routing</h2><dl><div><dt>Structured generation</dt><dd>{provider.data.structuredGeneration.providerName} · {provider.data.structuredGeneration.implementation} · {provider.data.structuredGeneration.available ? 'available' : 'offline'}</dd></div><div><dt>Embedding</dt><dd>{provider.data.embedding.providerName} · {provider.data.embedding.implementation} · {provider.data.embedding.available ? 'available' : 'offline'}</dd></div></dl></article></section></>}
  </main>
}
