import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ShieldCheck, UsersRound } from 'lucide-react'
import { useSearchParams } from 'react-router-dom'
import { getErrorMessage } from '../../lib/api/error-adapter'
import { useAuth } from '../auth/auth-context'
import { adminUsersKey, getAdminUsers, updateAdminUserEnabled, updateAdminUserRoles } from './admin.api'

export function AdminUsersPage() {
  const [params, setParams] = useSearchParams(); const page = Math.max(0, Number(params.get('page') || 0)); const keyword = params.get('keyword') || ''; const role = params.get('role') || ''
  const { currentUser } = useAuth(); const client = useQueryClient()
  const users = useQuery({ queryKey: [...adminUsersKey, page, keyword, role], queryFn: () => getAdminUsers({ page, size: 10, sort: 'createdAt,desc', ...(keyword ? { keyword } : {}), ...(role ? { role } : {}) }) })
  const refresh = () => client.invalidateQueries({ queryKey: adminUsersKey })
  const roles = useMutation({ mutationFn: ({ id, role }: { id: string; role: string }) => updateAdminUserRoles(id, [role]), onSuccess: refresh })
  const enabled = useMutation({ mutationFn: ({ id, value }: { id: string; value: boolean }) => updateAdminUserEnabled(id, value), onSuccess: refresh })
  return <main className="admin-page"><header className="admin-page__hero"><div><span>Identity operations</span><h1>Quản lý người dùng</h1><p>Role và trạng thái tài khoản được cập nhật trực tiếp tại Auth Service.</p></div><UsersRound /></header><form className="admin-toolbar" onSubmit={(e) => { e.preventDefault(); setParams({ ...(keyword ? { keyword } : {}), ...(role ? { role } : {}), page: '0' }) }}><label>Tìm kiếm<input value={keyword} onChange={(e) => setParams({ keyword: e.target.value, ...(role ? { role } : {}), page: '0' })} placeholder="Email hoặc họ tên" /></label><label>Role<select value={role} onChange={(e) => setParams({ ...(keyword ? { keyword } : {}), role: e.target.value, page: '0' })}><option value="">Tất cả</option><option>CANDIDATE</option><option>EMPLOYER</option><option>ADMIN</option></select></label></form>{users.isError && <p className="admin-feedback admin-feedback--error">{getErrorMessage(users.error)}</p>}{users.data && <section className="admin-grid admin-grid--three">{users.data.content.map((user) => <article className="admin-card" key={user.id}><div className="admin-card__top"><div><h2>{user.fullName}</h2><p>{user.email}</p></div><span className={`admin-badge ${user.enabled ? '' : 'admin-badge--off'}`}>{user.enabled ? 'ACTIVE' : 'DISABLED'}</span></div><dl><div><dt>Role</dt><dd>{user.roles.join(', ')}</dd></div><div><dt>Verified</dt><dd>{user.verified ? 'Có' : 'Chưa'}</dd></div><div><dt>User ID</dt><dd>{user.id}</dd></div></dl><div className="admin-card__actions"><select aria-label={`Role ${user.email}`} value={user.roles.length === 1 ? user.roles[0] : ''} disabled={user.id === currentUser?.id || roles.isPending} onChange={(e) => roles.mutate({ id: user.id, role: e.target.value })}><option value="" disabled>Nhiều role</option><option>CANDIDATE</option><option>EMPLOYER</option><option>ADMIN</option></select><button className="admin-button admin-button--secondary" disabled={user.id === currentUser?.id || enabled.isPending} onClick={() => enabled.mutate({ id: user.id, value: !user.enabled })}>{user.enabled ? 'Vô hiệu hóa' : 'Kích hoạt'}</button></div></article>)}</section>}{users.data && <nav className="admin-pagination"><button className="admin-button admin-button--secondary" disabled={users.data.first} onClick={() => setParams({ ...(keyword ? { keyword } : {}), ...(role ? { role } : {}), page: String(page - 1) })}>Trước</button><span>Trang {users.data.number + 1}/{Math.max(1, users.data.totalPages)}</span><button className="admin-button admin-button--secondary" disabled={users.data.last} onClick={() => setParams({ ...(keyword ? { keyword } : {}), ...(role ? { role } : {}), page: String(page + 1) })}>Sau</button></nav>}<aside className="admin-feedback"><ShieldCheck size={14} /> Admin hiện tại không thể tự gỡ ADMIN hoặc tự vô hiệu hóa.</aside></main>
}
