import { useQuery } from '@tanstack/react-query'
import { FileUser } from 'lucide-react'
import { Link, useSearchParams } from 'react-router-dom'
import { APPLICATION_STATUSES, type ApplicationStatus } from '../../types/models/application'
import { applicationStatusLabels } from '../applications/application-presenter'
import { adminApplicationsKey, getAdminApplications } from './admin.api'

export function AdminApplicationsPage() {
  const [params, setParams] = useSearchParams(); const page = Math.max(0, Number(params.get('page') || 0)); const status = (params.get('status') || '') as ApplicationStatus | ''; const companyId = params.get('companyId') || ''; const candidateId = params.get('candidateId') || ''
  const applications = useQuery({ queryKey: [...adminApplicationsKey, page, status, companyId, candidateId], queryFn: () => getAdminApplications({ page, size: 10, sort: 'appliedAt,desc', ...(status ? { status } : {}), ...(companyId ? { companyId } : {}), ...(candidateId ? { candidateId } : {}) }) })
  const update = (next: Record<string, string>) => setParams({ ...(status ? { status } : {}), ...(companyId ? { companyId } : {}), ...(candidateId ? { candidateId } : {}), ...next })
  return <main className="admin-page"><header className="admin-page__hero"><div><span>Global recruitment audit</span><h1>Quản lý Application</h1><p>Truy vấn toàn hệ thống với quyền ADMIN explicit tại Application Service.</p></div><FileUser /></header><section className="admin-toolbar"><label>Trạng thái<select value={status} onChange={(e) => update({ status: e.target.value, page: '0' })}><option value="">Tất cả</option>{APPLICATION_STATUSES.map((s) => <option key={s} value={s}>{applicationStatusLabels[s]}</option>)}</select></label><label>Company ID<input value={companyId} onChange={(e) => update({ companyId: e.target.value, page: '0' })} /></label><label>Candidate ID<input value={candidateId} onChange={(e) => update({ candidateId: e.target.value, page: '0' })} /></label></section>{applications.data && <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Candidate</th><th>Status</th><th>Company</th><th>Job</th><th>Applied</th><th /></tr></thead><tbody>{applications.data.content.map((app) => <tr key={app.id}><td>{app.candidateProfileSnapshot?.displayName || app.candidateId}</td><td>{applicationStatusLabels[app.status]}</td><td>{app.companyId}</td><td>{app.jobId}</td><td>{new Date(app.appliedAtInstant ?? app.appliedAt).toLocaleString('vi-VN')}</td><td><Link to={`/admin/applications/${app.id}`}>Chi tiết</Link></td></tr>)}</tbody></table></div>}{applications.data && <nav className="admin-pagination"><button className="admin-button admin-button--secondary" disabled={!applications.data.hasPrevious} onClick={() => update({ page: String(page - 1) })}>Trước</button><span>Trang {applications.data.page + 1}/{Math.max(1, applications.data.totalPages)}</span><button className="admin-button admin-button--secondary" disabled={!applications.data.hasNext} onClick={() => update({ page: String(page + 1) })}>Sau</button></nav>}</main>
}
