// Original combinations of shared layout, palette, typography and section order.
// Existing IDs are retained so older saved CVs continue to load unchanged.
export const cvPresetDefinitions = {
  'classic': {"name":"Classic Green","category":"Cổ điển","description":"Một cột nhẹ nhàng với đường nhấn xanh.","bestFor":"Kinh doanh, vận hành","layout":"single","theme":"emerald","fontFamily":"Arial","density":"normal","arrangement":"experience"},
  'professional': {"name":"Executive","category":"Chuyên nghiệp","description":"Tiêu đề trang trọng, ưu tiên thành tựu quản lý.","bestFor":"Quản lý, tài chính","layout":"header","theme":"navy","fontFamily":"Georgia","density":"compact","arrangement":"experience"},
  'modern': {"name":"Modern Mint","category":"Hiện đại","description":"Mảng đầu trang xanh ngọc và nhịp chữ thoáng.","bestFor":"Sản phẩm, dịch vụ","layout":"header","theme":"teal","fontFamily":"Inter","density":"comfortable","arrangement":"experience"},
  'ats': {"name":"ATS Focus","category":"Cổ điển","description":"Luồng đọc tuyến tính, ít trang trí và rõ thông tin.","bestFor":"Ứng tuyển qua hệ thống ATS","layout":"single","theme":"gray","fontFamily":"Arial","density":"compact","arrangement":"experience"},
  'student': {"name":"First Step","category":"Sinh viên / Fresher","description":"Học vấn và dự án nổi bật trước kinh nghiệm.","bestFor":"Sinh viên mới tốt nghiệp","layout":"header","theme":"blue","fontFamily":"Inter","density":"normal","arrangement":"education"},
  'modern-professional': {"name":"Modern Professional","category":"Chuyên nghiệp","description":"Hồ sơ chuyên môn với cột kỹ năng gọn bên phải.","bestFor":"Chuyên viên nhiều kỹ năng","layout":"sidebar-right","theme":"teal","fontFamily":"Roboto","density":"normal","arrangement":"experience"},
  'corporate': {"name":"Corporate","category":"Chuyên nghiệp","description":"Tông xanh doanh nghiệp, cấu trúc một cột cô đọng.","bestFor":"Ngân hàng, nhân sự","layout":"single","theme":"navy","fontFamily":"Arial","density":"compact","arrangement":"experience"},
  'minimal': {"name":"Minimal","category":"Hiện đại","description":"Khoảng trắng rộng, nội dung ngắn và dễ quét.","bestFor":"Chuyên viên đa ngành","layout":"single","theme":"gray","fontFamily":"Inter","density":"comfortable","arrangement":"experience"},
  'clean-grid': {"name":"Clean Grid","category":"Hiện đại","description":"Hai vùng thông tin cân bằng với nhấn màu xanh.","bestFor":"Vận hành, phân tích","layout":"sidebar-right","theme":"blue","fontFamily":"Open Sans","density":"normal","arrangement":"experience"},
  'sidebar-emerald': {"name":"Sidebar Emerald","category":"Hiện đại","description":"Học vấn và kỹ năng gom vào cột xanh lá bên trái.","bestFor":"Hồ sơ kỹ năng đa dạng","layout":"sidebar-left","theme":"emerald","fontFamily":"Inter","density":"normal","arrangement":"experience"},
  'sidebar-navy': {"name":"Sidebar Navy","category":"Hiện đại","description":"Cột thông tin nền xanh hải quân, chữ rõ và gọn.","bestFor":"Chuyên viên cao cấp","layout":"sidebar-left","theme":"navy","fontFamily":"Open Sans","density":"compact","arrangement":"experience"},
  'developer': {"name":"Developer","category":"Công nghệ","description":"Dự án lên trước để thể hiện công nghệ đã sử dụng.","bestFor":"Lập trình viên","layout":"sidebar-left","theme":"teal","fontFamily":"Roboto","density":"normal","arrangement":"projects"},
  'software-engineer': {"name":"Software Engineer","category":"Công nghệ","description":"Một cột tuyến tính, ưu tiên kinh nghiệm kỹ thuật.","bestFor":"Kỹ sư phần mềm","layout":"single","theme":"blue","fontFamily":"Inter","density":"normal","arrangement":"experience"},
  'data-professional': {"name":"Data Professional","category":"Công nghệ","description":"Cột kỹ năng bên phải và dự án dữ liệu nổi bật.","bestFor":"Phân tích dữ liệu, BI","layout":"sidebar-right","theme":"purple","fontFamily":"Open Sans","density":"compact","arrangement":"projects"},
  'ai-engineer': {"name":"AI Engineer","category":"Công nghệ","description":"Đầu trang đậm, ưu tiên mô hình và dự án triển khai.","bestFor":"Kỹ sư AI, ML","layout":"header","theme":"navy","fontFamily":"Roboto","density":"normal","arrangement":"projects"},
  'creative-accent': {"name":"Creative Accent","category":"Sáng tạo","description":"Mảng tím nổi bật, nội dung rộng rãi và thoáng.","bestFor":"Thiết kế, nội dung","layout":"header","theme":"purple","fontFamily":"Inter","density":"comfortable","arrangement":"projects"},
  'portfolio': {"name":"Portfolio","category":"Sáng tạo","description":"Dự án là trung tâm, cột phụ giữ kỹ năng ngắn gọn.","bestFor":"Thiết kế sản phẩm, freelancer","layout":"sidebar-right","theme":"burgundy","fontFamily":"Georgia","density":"comfortable","arrangement":"projects"},
  'marketing': {"name":"Marketing","category":"Sáng tạo","description":"Nhấn sắc cam và ưu tiên kết quả chiến dịch.","bestFor":"Marketing, truyền thông","layout":"header","theme":"orange","fontFamily":"Open Sans","density":"normal","arrangement":"experience"},
  'graduate': {"name":"Graduate","category":"Sinh viên / Fresher","description":"Học vấn trước tiên, phần phụ gọn phía trái.","bestFor":"Tân cử nhân","layout":"sidebar-left","theme":"blue","fontFamily":"Roboto","density":"comfortable","arrangement":"education"},
  'intern': {"name":"Intern","category":"Sinh viên / Fresher","description":"Một cột dễ hoàn thiện cho hồ sơ đầu tiên.","bestFor":"Thực tập sinh","layout":"single","theme":"teal","fontFamily":"Arial","density":"comfortable","arrangement":"education"},
  'fresher': {"name":"Fresher","category":"Sinh viên / Fresher","description":"Dự án thực hành và nền tảng học tập cùng tông xanh.","bestFor":"Ứng viên chưa có kinh nghiệm","layout":"header","theme":"emerald","fontFamily":"Open Sans","density":"normal","arrangement":"education"},
  'academic': {"name":"Academic","category":"Sinh viên / Fresher","description":"Chữ có chân, ưu tiên nền tảng học thuật và nghiên cứu.","bestFor":"Học thuật, nghiên cứu","layout":"single","theme":"navy","fontFamily":"Times New Roman","density":"comfortable","arrangement":"education"},
  'classic-formal': {"name":"Classic Formal","category":"Cổ điển","description":"Chữ truyền thống, đường nét tiết chế và nghiêm túc.","bestFor":"Hành chính, pháp chế","layout":"single","theme":"burgundy","fontFamily":"Times New Roman","density":"normal","arrangement":"experience"},
  'elegant': {"name":"Elegant","category":"Cổ điển","description":"Sắc trầm, đầu trang thanh lịch và khoảng cách thoáng.","bestFor":"Tư vấn, quản lý khách hàng","layout":"header","theme":"burgundy","fontFamily":"Georgia","density":"comfortable","arrangement":"experience"},
} as const

export const cvTemplateCategories = ['Chuyên nghiệp', 'Hiện đại', 'Công nghệ', 'Sáng tạo', 'Sinh viên / Fresher', 'Cổ điển'] as const
