import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowDown, ArrowLeft, ArrowUp, Download, Eye, Plus, Save, Sparkles, Trash2 } from 'lucide-react'
import { type ReactNode, useEffect, useState } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { cvApi, saveBlob } from './cv.api'
import { CvPreview } from './components/CvPreview'
import { cvTemplates } from './cv.templates'
import { emptyCvContent, type CvCertification, type CvContent, type CvEducation, type CvExperience, type CvNamedItem, type CvProject, type CvTemplateId, type SaveCvPayload } from './cv.types'
import './cv-builder.css'

const blankExperience = (): CvExperience => ({ position: '', company: '', startDate: '', endDate: '', description: '' })
const blankEducation = (): CvEducation => ({ school: '', degree: '', startDate: '', endDate: '', description: '' })
const blankProject = (): CvProject => ({ name: '', url: '', description: '' })
const blankCertification = (): CvCertification => ({ name: '', issuer: '', date: '' })
const blankNamedItem = (): CvNamedItem => ({ name: '', date: '', description: '' })

export function CvEditorPage() {
  const { id } = useParams()
  const [params] = useSearchParams()
  const navigate = useNavigate()
  const queryClient = useQueryClient()
  const initialTemplate = cvTemplates.some((item) => item.id === params.get('template')) ? params.get('template') as CvTemplateId : 'classic'
  const [title, setTitle] = useState('CV tiếng Việt')
  const [templateId, setTemplateId] = useState<CvTemplateId>(initialTemplate)
  const [content, setContent] = useState<CvContent>(emptyCvContent)
  const [mobileTab, setMobileTab] = useState<'content' | 'preview'>('content')
  const [loadedId, setLoadedId] = useState<string | null>(null)
  const existing = useQuery({ queryKey: ['candidate-cv', id], queryFn: () => cvApi.get(id!), enabled: Boolean(id) })

  useEffect(() => {
    if (!existing.data || loadedId === existing.data.id) return
    setTitle(existing.data.title); setTemplateId(existing.data.templateId); setContent(existing.data.content); setLoadedId(existing.data.id)
  }, [existing.data, loadedId])

  const payload = (): SaveCvPayload => ({ title: title.trim() || 'CV tiếng Việt', templateId, language: 'vi', content })
  const save = useMutation({ mutationFn: () => id ? cvApi.update(id, payload()) : cvApi.create(payload()), onSuccess: async (saved) => { await queryClient.invalidateQueries({ queryKey: ['candidate-cvs'] }); await queryClient.invalidateQueries({ queryKey: ['candidate-cv', saved.id] }); if (!id) navigate(`/cv/${saved.id}/edit`, { replace: true }) } })
  const autofill = useMutation({ mutationFn: () => cvApi.createFromProfile(title.trim() || 'CV từ hồ sơ', templateId), onSuccess: async (saved) => { await queryClient.invalidateQueries({ queryKey: ['candidate-cvs'] }); navigate(`/cv/${saved.id}/edit`, { replace: true }) } })
  const download = useMutation({ mutationFn: async () => { const saved = id ? await cvApi.update(id, payload()) : await cvApi.create(payload()); return { saved, blob: await cvApi.download(saved.id) } }, onSuccess: ({ saved, blob }) => { saveBlob(blob, `${saved.title}.pdf`); if (!id) navigate(`/cv/${saved.id}/edit`, { replace: true }) } })

  const setPersonal = (field: keyof CvContent['personalInfo'], value: string) => setContent((current) => ({ ...current, personalInfo: { ...current.personalInfo, [field]: value } }))
  const updateList = <K extends 'experiences' | 'education' | 'projects' | 'certifications' | 'awards' | 'activities'>(key: K, index: number, value: CvContent[K][number]) => setContent((current) => ({ ...current, [key]: current[key].map((item, itemIndex) => itemIndex === index ? value : item) }))
  const removeList = (key: 'experiences' | 'education' | 'projects' | 'certifications' | 'awards' | 'activities', index: number) => setContent((current) => ({ ...current, [key]: current[key].filter((_, itemIndex) => itemIndex !== index) }))
  const moveList = (key: 'experiences' | 'education' | 'projects' | 'certifications' | 'awards' | 'activities', index: number, direction: -1 | 1) => setContent((current) => { const next = [...current[key]] as CvNamedItem[]; const target = index + direction; if (target < 0 || target >= next.length) return current; [next[index], next[target]] = [next[target], next[index]]; return { ...current, [key]: next } as CvContent })

  if (id && existing.isLoading) return <main className="cv-page"><div className="cv-state">Đang mở CV…</div></main>
  if (id && existing.isError) return <main className="cv-page"><div className="cv-state cv-state--error">Không tìm thấy CV hoặc bạn không có quyền truy cập.</div></main>

  return <main className="cv-editor">
    <header className="cv-editor__toolbar"><Link to="/cv"><ArrowLeft /> CV của tôi</Link><input aria-label="Tên CV" value={title} maxLength={150} onChange={(event) => setTitle(event.target.value)} /><select aria-label="Mẫu CV" value={templateId} onChange={(event) => setTemplateId(event.target.value as CvTemplateId)}>{cvTemplates.map((template) => <option value={template.id} key={template.id}>{template.name}</option>)}</select><div className="cv-editor__toolbar-actions">{!id && <button type="button" onClick={() => autofill.mutate()} disabled={autofill.isPending}><Sparkles /> Tạo từ hồ sơ</button>}<button type="button" onClick={() => setMobileTab('preview')}><Eye /> Xem trước</button><button type="button" onClick={() => download.mutate()} disabled={download.isPending}><Download /> PDF</button><button className="is-primary" type="button" onClick={() => save.mutate()} disabled={save.isPending}><Save /> {save.isPending ? 'Đang lưu…' : 'Lưu CV'}</button></div></header>
    {(save.isError || autofill.isError || download.isError) && <div className="cv-editor__error">Không thể hoàn tất thao tác. Vui lòng kiểm tra dữ liệu và thử lại.</div>}
    <div className="cv-editor__mobile-tabs"><button className={mobileTab === 'content' ? 'is-active' : ''} onClick={() => setMobileTab('content')} type="button">Nội dung</button><button className={mobileTab === 'preview' ? 'is-active' : ''} onClick={() => setMobileTab('preview')} type="button">Xem trước</button></div>
    <div className="cv-editor__workspace">
      <aside className={`cv-editor__form${mobileTab === 'preview' ? ' is-mobile-hidden' : ''}`}>
        <nav className="cv-editor__section-nav" aria-label="Các phần CV">{[['personal','Thông tin'],['summary','Giới thiệu'],['experience','Kinh nghiệm'],['education','Học vấn'],['skills','Kỹ năng'],['projects','Dự án'],['certifications','Chứng chỉ'],['awards','Giải thưởng'],['activities','Hoạt động']].map(([anchor,label]) => <a key={anchor} href={`#cv-${anchor}`}>{label}</a>)}</nav>
        <EditorPanel id="cv-personal" title="Thông tin cá nhân"><div className="cv-form-grid"><Field label="Họ và tên" value={content.personalInfo.fullName} onChange={(value) => setPersonal('fullName', value)} /><Field label="Chức danh" value={content.personalInfo.headline} onChange={(value) => setPersonal('headline', value)} /><Field label="Email" type="email" value={content.personalInfo.email} onChange={(value) => setPersonal('email', value)} /><Field label="Điện thoại" value={content.personalInfo.phone} onChange={(value) => setPersonal('phone', value)} /><Field label="Địa điểm" value={content.personalInfo.location} onChange={(value) => setPersonal('location', value)} /><Field label="Website" value={content.personalInfo.website} onChange={(value) => setPersonal('website', value)} /></div></EditorPanel>
        <EditorPanel id="cv-summary" title="Mục tiêu / Giới thiệu"><TextArea label="Giới thiệu bản thân" value={content.summary} onChange={(value) => setContent((current) => ({ ...current, summary: value }))} /></EditorPanel>
        <EditorPanel id="cv-experience" title="Kinh nghiệm" onAdd={() => setContent((current) => ({ ...current, experiences: [...current.experiences, blankExperience()] }))}>{content.experiences.map((item, index) => <ItemCard key={index} index={index} count={content.experiences.length} onRemove={() => removeList('experiences', index)} onMove={(direction) => moveList('experiences', index, direction)}><div className="cv-form-grid"><Field label="Vị trí" value={item.position} onChange={(value) => updateList('experiences', index, { ...item, position: value })} /><Field label="Công ty" value={item.company} onChange={(value) => updateList('experiences', index, { ...item, company: value })} /><Field label="Bắt đầu" value={item.startDate} onChange={(value) => updateList('experiences', index, { ...item, startDate: value })} /><Field label="Kết thúc" value={item.endDate} onChange={(value) => updateList('experiences', index, { ...item, endDate: value })} /></div><TextArea label="Mô tả và thành tựu" value={item.description} onChange={(value) => updateList('experiences', index, { ...item, description: value })} /></ItemCard>)}</EditorPanel>
        <EditorPanel id="cv-education" title="Học vấn" onAdd={() => setContent((current) => ({ ...current, education: [...current.education, blankEducation()] }))}>{content.education.map((item, index) => <ItemCard key={index} index={index} count={content.education.length} onRemove={() => removeList('education', index)} onMove={(direction) => moveList('education', index, direction)}><div className="cv-form-grid"><Field label="Trường" value={item.school} onChange={(value) => updateList('education', index, { ...item, school: value })} /><Field label="Bằng cấp / Chuyên ngành" value={item.degree} onChange={(value) => updateList('education', index, { ...item, degree: value })} /><Field label="Bắt đầu" value={item.startDate} onChange={(value) => updateList('education', index, { ...item, startDate: value })} /><Field label="Kết thúc" value={item.endDate} onChange={(value) => updateList('education', index, { ...item, endDate: value })} /></div><TextArea label="Mô tả" value={item.description} onChange={(value) => updateList('education', index, { ...item, description: value })} /></ItemCard>)}</EditorPanel>
        <EditorPanel id="cv-skills" title="Kỹ năng" onAdd={() => setContent((current) => ({ ...current, skills: [...current.skills, ''] }))}>{content.skills.map((skill, index) => <div className="cv-skill-row" key={index}><input aria-label={`Kỹ năng ${index + 1}`} value={skill} maxLength={120} onChange={(event) => setContent((current) => ({ ...current, skills: current.skills.map((value, itemIndex) => itemIndex === index ? event.target.value : value) }))} /><button type="button" aria-label="Xóa kỹ năng" onClick={() => setContent((current) => ({ ...current, skills: current.skills.filter((_, itemIndex) => itemIndex !== index) }))}><Trash2 /></button></div>)}</EditorPanel>
        <EditorPanel id="cv-projects" title="Dự án" onAdd={() => setContent((current) => ({ ...current, projects: [...current.projects, blankProject()] }))}>{content.projects.map((item, index) => <ItemCard key={index} index={index} count={content.projects.length} onRemove={() => removeList('projects', index)} onMove={(direction) => moveList('projects', index, direction)}><div className="cv-form-grid"><Field label="Tên dự án" value={item.name} onChange={(value) => updateList('projects', index, { ...item, name: value })} /><Field label="Liên kết" value={item.url} onChange={(value) => updateList('projects', index, { ...item, url: value })} /></div><TextArea label="Mô tả" value={item.description} onChange={(value) => updateList('projects', index, { ...item, description: value })} /></ItemCard>)}</EditorPanel>
        <EditorPanel id="cv-certifications" title="Chứng chỉ" onAdd={() => setContent((current) => ({ ...current, certifications: [...current.certifications, blankCertification()] }))}>{content.certifications.map((item, index) => <ItemCard key={index} index={index} count={content.certifications.length} onRemove={() => removeList('certifications', index)} onMove={(direction) => moveList('certifications', index, direction)}><div className="cv-form-grid"><Field label="Tên chứng chỉ" value={item.name} onChange={(value) => updateList('certifications', index, { ...item, name: value })} /><Field label="Đơn vị cấp" value={item.issuer} onChange={(value) => updateList('certifications', index, { ...item, issuer: value })} /><Field label="Thời gian" value={item.date} onChange={(value) => updateList('certifications', index, { ...item, date: value })} /></div></ItemCard>)}</EditorPanel>
        <NamedItemsPanel id="cv-awards" title="Giải thưởng" items={content.awards} onAdd={() => setContent((current) => ({ ...current, awards: [...current.awards, blankNamedItem()] }))} onChange={(index, item) => updateList('awards', index, item)} onRemove={(index) => removeList('awards', index)} onMove={(index, direction) => moveList('awards', index, direction)} />
        <NamedItemsPanel id="cv-activities" title="Hoạt động" items={content.activities} onAdd={() => setContent((current) => ({ ...current, activities: [...current.activities, blankNamedItem()] }))} onChange={(index, item) => updateList('activities', index, item)} onRemove={(index) => removeList('activities', index)} onMove={(index, direction) => moveList('activities', index, direction)} />
      </aside>
      <section className={`cv-editor__preview${mobileTab === 'content' ? ' is-mobile-hidden' : ''}`}><div className="cv-editor__preview-sticky"><span>Bản xem trước trực tiếp · A4</span><CvPreview content={content} templateId={templateId} /></div></section>
    </div>
  </main>
}

function EditorPanel({ id, title, onAdd, children }: { id: string; title: string; onAdd?: () => void; children: ReactNode }) { return <section className="cv-editor-panel" id={id}><header><h2>{title}</h2>{onAdd && <button type="button" onClick={onAdd}><Plus /> Thêm</button>}</header>{children}</section> }
function Field({ label, value, onChange, type = 'text' }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <label className="cv-field"><span>{label}</span><input type={type} value={value} maxLength={2048} onChange={(event) => onChange(event.target.value)} /></label> }
function TextArea({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="cv-field"><span>{label}</span><textarea value={value} maxLength={5000} rows={4} onChange={(event) => onChange(event.target.value)} /></label> }
function ItemCard({ index, count, onRemove, onMove, children }: { index: number; count: number; onRemove: () => void; onMove: (direction: -1 | 1) => void; children: ReactNode }) { return <div className="cv-editor-item"><div className="cv-editor-item__tools"><strong>Mục {index + 1}</strong><button type="button" disabled={index === 0} onClick={() => onMove(-1)} aria-label="Di chuyển lên"><ArrowUp /></button><button type="button" disabled={index === count - 1} onClick={() => onMove(1)} aria-label="Di chuyển xuống"><ArrowDown /></button><button type="button" className="is-danger" onClick={onRemove} aria-label="Xóa mục"><Trash2 /></button></div>{children}</div> }
function NamedItemsPanel({ id, title, items, onAdd, onChange, onRemove, onMove }: { id: string; title: string; items: CvNamedItem[]; onAdd: () => void; onChange: (index: number, item: CvNamedItem) => void; onRemove: (index: number) => void; onMove: (index: number, direction: -1 | 1) => void }) { return <EditorPanel id={id} title={title} onAdd={onAdd}>{items.map((item, index) => <ItemCard key={index} index={index} count={items.length} onRemove={() => onRemove(index)} onMove={(direction) => onMove(index, direction)}><div className="cv-form-grid"><Field label="Tên" value={item.name} onChange={(value) => onChange(index, { ...item, name: value })} /><Field label="Thời gian" value={item.date} onChange={(value) => onChange(index, { ...item, date: value })} /></div><TextArea label="Mô tả" value={item.description} onChange={(value) => onChange(index, { ...item, description: value })} /></ItemCard>)}</EditorPanel> }
