spring:

  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]
      - optional:file:../../.env[.properties]

  application:
    name: user-service

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: ${JPA_SHOW_SQL}

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        default_schema: user_service
        format_sql: true
        jdbc:
          time_zone: ${JPA_TIME_ZONE}

  flyway:
    enabled: true
    baseline-on-migrate: true
    create-schemas: true
    schemas: user_service
    default-schema: user_service
    table: user_service_flyway_schema_history
    locations: classpath:db/migration

server:
  port: ${USER_SERVICE_PORT}

springdoc:

  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

logging:

  level:

    root: INFO

    org.springframework: INFO

    org.springframework.security: INFO

    org.hibernate.SQL: DEBUG

    org.hibernate.orm.jdbc.bind: TRACE

management:

  endpoints:

    web:

      exposure:

        include: health,info

  endpoint:

    health:

      show-details: always

storage:

  endpoint: ${MINIO_ENDPOINT}

  access-key: ${MINIO_ACCESS_KEY}

  secret-key: ${MINIO_SECRET_KEY}

  bucket: ${USER_MINIO_BUCKET}

  auto-create-bucket: ${USER_MINIO_AUTO_CREATE_BUCKET}
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
